### ISSUE TITLE
Proposal to manage language files

### ISSUE THREAD

**Issue by bovirus** [Maxstupo/ydl-ui_i18n#44]
@Maxstupo 

Hello.

You relasead 19 hours ago the new english language file and 19 hours ago your released a new program version.

If you can please elave to the translator the time to update language files before to release a new program version.
Otherwise new version is updated for english but not for other langauges.

To advise the translator about a new language release (github notify seems not so tempestive) could select different options

- create a mailing list with all translator emails and send a unique message to all translator with a simple communication about new english language.
 
- Move translation files on host like Transiflex that has a valid notify system that advise translator about a new language file vesrion.
 
Thanks.

**Comment by Maxstupo** [comment]
Yeah, I can do that (I will release a patch once a few more translations are done). I think moving the files to a host would be a good idea, but ideally the host would have to offer a free option. GitHub integration would be great too. 

Another idea would be to use an auto update feature that would update the translation files when available (separate from application updates).

**Comment by bovirus** [comment]
@Maxstupo 

Transiflex is free.
It has a good notification system.
And should have integration with Github.

**Comment by Maxstupo** [comment]
@bovirus 

Oh, didn't see that it had a separate open source section. I will check it out.

**Comment by Maxstupo** [comment]
@bovirus 

I had a look at Transifex, it looks good. I'm planning to switch the repository workflow to using it.

https://www.transifex.com/ydl-apps/ydl-ui

**Comment by bovirus** [comment]
@Maxstupo 

Thanks.
I made a request to joint to the team for Italian language.

**Comment by Maxstupo** [comment]
@bovirus 

> **_- Add green tag for localization_**
> 
> If you can please add green tag for localization (after license/release/download/build)

Can't seem to find a dynamic one for Transifex, but could do something like this:

<a href="https://www.transifex.com/ydl-apps/ydl-ui">
<img src="https://img.shields.io/badge/localized-Transifex-success?svg=true"/>
</a>

</br>
or
</br>

<a href="https://www.transifex.com/ydl-apps/ydl-ui">
<img src="https://img.shields.io/badge/localized_with-Transifex-success?svg=true"/>
</a>

**Comment by bovirus** [comment]
@Maxstupo 

Yes. A badge that show on the top the link to transiflex page.

![image](https://user-images.githubusercontent.com/1262554/134545333-b3a14e29-c0e2-4ff9-838c-f64c60f262df.png)

I beleiev that is not necessary the percentage of tarnslation.

Of coutse on part where you explain about Translations ection now mention link on Transiflex.

**Comment by Maxstupo** [comment]
@bovirus
 
Done

**Comment by bovirus** [comment]
@Maxstupo 

Thanks.
You can close the ticket.
